apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: hello-world
        image: benjilee5453/hello-world:v1
        ports:
        - containerPort: 5000
