apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: benjilee5453/hello-world:v1.2.1
        imagePullPolicy: Never
        ports:
        - name: http 
          containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health_check
            port: http
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          # - name: POD_NAME_1
          #   valueFrom:
          #     fieldRef:
          #       fieldPath: metadata.name
        command:
          - sh
          - -c
          - cd /app && python app.py
        resources:
          limits:
            cpu: 100m
            memory: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000