apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: hello-world
        image: benjilee5453/hello-world:v3
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health_check
            port: 5000
          initialDelaySeconds: 3
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                  fieldPath: metadata.name
